#!/bin/bash

# Audit script.
# This script requires Bash 4 due to the associative arrays.

# Create a dictionary or associative array to store user details.
declare -A users

# Read from the input and split based on the IFS (internal field separator)
# and take the fields as user and password in order.
#
# The input for the loop attempts to read from STDIN, and filters  two choices
# for input using ${input:-defaultvalue} syntax. It will attempt to read from
# ${1} first (the first argument to the script) before attempting to read from
# /dev/stdin instead.
while IFS=':' read -r USER PASSWORD
do
    # Add the fields to the associative array.
    users+=(["${USER}"]="${PASSWORD}")
done < "${1:-/dev/stdin}"

# Iterate the dictionary and display it.
for i in "${!users[@]}"
do
    # Echo and enable tabs (-e)
    echo -e "user:" "$i" "\tpassword:" "${users[$i]}"
done
