#!/usr/bin/env bash

# Audit script.
# This script requires Bash 4 due to the associative arrays.

# Create a dictionary or associative array to store user details.
declare -A users

# Read from stdin and split based on the IFS (internal field separator)
# and take the fields as user and password in order.
while IFS=':' read USER PASSWORD
do
    # Add the fields to the associative array.
    users+=(["${USER}"]="${PASSWORD}")
done < /dev/stdin

# Iterate the dictionary and display it.
for i in "${!users[@]}"
do
    # Echo and enable tabs (-e)
    echo -e "user:" "$i" "\tpassword:" "${users[$i]}"
done
